### ISSUE TITLE
Profile region not configured correctly by the install command

### ISSUE THREAD

**Issue by eyalroth** [CircleCI-Public/aws-sam-serverless-orb#26]
## Orb version:
3.0

## What happened:

`install` command does not configure profile region properly:
```yml
- sam/install:
    aws-region: MY_REGION
    profile-name: myprofile

- run: cat ~/.aws/config

- run: aws configure list --profile myprofile

- run: sam package --profile myprofile ...
```

```
cat ~/.aws/config
[default]
region = *********

aws configure list --profile myprofile
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                    myprofile           manual    --profile
access_key     **************** shared-credentials-file    
secret_key     **************** shared-credentials-file    
    region                *********              env    ['MY_REGION', 'AWS_DEFAULT_REGION']


sam package --profile myprofile ...
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "samcli/lib/cli_validation/image_repository_validation.py", line 76, in wrapped
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 152, in wrapped
  File "samcli/lib/telemetry/metric.py", line 121, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/lib/telemetry/metric.py", line 84, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "samcli/commands/package/command.py", line 176, in cli
  File "samcli/commands/package/command.py", line 225, in do_cli
  File "samcli/commands/package/package_context.py", line 105, in run
  File "boto3/__init__.py", line 91, in client
  File "boto3/session.py", line 263, in client
  File "botocore/session.py", line 838, in create_client
  File "botocore/client.py", line 85, in create_client
  File "botocore/client.py", line 308, in _get_client_args
  File "botocore/args.py", line 73, in get_client_args
  File "botocore/args.py", line 153, in compute_client_args
  File "botocore/args.py", line 218, in _compute_endpoint_config
  File "botocore/args.py", line 301, in _resolve_endpoint
  File "botocore/client.py", line 382, in resolve
  File "botocore/regions.py", line 134, in construct_endpoint
  File "botocore/regions.py", line 148, in _endpoint_for_partition
botocore.exceptions.NoRegionError: You must specify a region.
```

## Expected behavior:

The `install` command should configure the profile region correctly so it would be detected by further sam CLI commands.

## Workaround:

Use `aws-cli/setup` version 1.4.0+ directly to configure the profile's region:

```yml
orbs:
  aws-cli: circleci/aws-cli@1.4.1
  sam: circleci/aws-sam-serverless@3.0

...
    steps:
      - aws-cli/setup:
          aws-region: MY_REGION
          profile-name: myprofile
          configure-profile-region: true
          configure-default-region: false

      - sam/install:
          configure-default-region: false
```

## Additional Information:

This seems to have been a problem in the aws-cli orb, fixed in [this PR](https://github.com/CircleCI-Public/aws-cli-orb/pull/64) that was merged in v1.4.0. It might be that updating the this orb to use aws-cli 1.40 (or later) will fix the problem.

**Comment by KyleTryon** [comment]
Hello,

We have released v4 of the SAM CLI, which now requires that the user install and configure the AWS CLI separately to avoid this issue as well as allow for more authentication methods.
