### ISSUE TITLE
ModuleNotFoundError: No module named 'configparser' at version 3.0.0

### ISSUE THREAD

**Issue by shunwen** [CircleCI-Public/aws-sam-serverless-orb#29]
## Orb version:

3.0.0

## What happened:

Failed with exception, worked fine with version 2.0.0

```
#!/bin/bash -eo pipefail
sam validate -t ./functions/template.yaml \
--region $AWS_DEFAULT_REGION \
--profile default \
--debug

Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1257, in invoke
  File "click/core.py", line 700, in make_context
  File "click/core.py", line 1048, in parse_args
  File "click/core.py", line 1630, in handle_parse_result
  File "click/core.py", line 123, in invoke_param_callback
  File "samcli/cli/options.py", line 42, in callback
  File "samcli/cli/context.py", line 78, in region
  File "samcli/cli/context.py", line 178, in _refresh_session
  File "boto3/__init__.py", line 35, in setup_default_session
  File "boto3/session.py", line 80, in __init__
  File "boto3/session.py", line 120, in _setup_loader
  File "botocore/session.py", line 685, in get_component
  File "botocore/session.py", line 924, in get_component
  File "botocore/session.py", line 158, in <lambda>
  File "botocore/session.py", line 241, in get_config_variable
  File "botocore/configprovider.py", line 313, in get_config_variable
  File "botocore/configprovider.py", line 410, in provide
  File "botocore/configprovider.py", line 471, in provide
  File "botocore/session.py", line 330, in get_scoped_config
  File "botocore/session.py", line 226, in _build_profile_map
  File "botocore/session.py", line 357, in full_config
  File "botocore/configloader.py", line 106, in load_config
  File "botocore/configloader.py", line 147, in raw_config_parse
  File "botocore/vendored/six.py", line 92, in __get__
  File "botocore/vendored/six.py", line 115, in _resolve
  File "botocore/vendored/six.py", line 82, in _import_module
ModuleNotFoundError: No module named 'configparser'
[11478] Failed to execute script __main__

Exited with code exit status 255
CircleCI received exit code 255
```

## Expected behavior:

Pass without exception

## Additional Information:

My circleci config is very simple

```
version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@3.0

workflows:
  main:
    jobs:
      - sam/deploy:
          name: deploy-production
          s3-bucket: production
          stack-name: production
          template: ./functions/template.yaml
          debug: true
          filters:
            branches:
              only: master

```

**Comment by thoward27** [comment]
@KyleTryon I see you as the most recent contributor to this repository. I am seeing the same thing as @shunwen. Note that this error was not present during my testing yesterday. 

Roughly, my configuration is:

```
version: '2.1'
orbs:
  sam: circleci/aws-sam-serverless@3.0
jobs:
  build_app:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run: sam build
workflows:
  my-workflow:
    jobs:
      - build_app
``` 

Any tips/tricks/solutions would be greatly appreciated! 

Also, if you are the wrong person for this type of issue, please let me know and I will direct my questions elsewhere
